namespace serialization;

enum Color : byte { Empty = 0, Black = 1, White = 2 }
struct Intersection {
  X:byte;
  Y:byte;
}
struct Placement {
  place:Intersection;
  player:Color;
}
table Board {
  places:[Placement];
  toMove:Color;
}
