package serialization;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameState.proto

public final class GameState {
  private GameState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Color}
   */
  public enum Color
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EMPTY = 0;</code>
     */
    EMPTY(0, 0),
    /**
     * <code>BLACK = 1;</code>
     */
    BLACK(1, 1),
    /**
     * <code>WHITE = 2;</code>
     */
    WHITE(2, 2),
    ;

    /**
     * <code>EMPTY = 0;</code>
     */
    public static final int EMPTY_VALUE = 0;
    /**
     * <code>BLACK = 1;</code>
     */
    public static final int BLACK_VALUE = 1;
    /**
     * <code>WHITE = 2;</code>
     */
    public static final int WHITE_VALUE = 2;


    public final int getNumber() { return value; }

    public static Color valueOf(int value) {
      switch (value) {
        case 0: return EMPTY;
        case 1: return BLACK;
        case 2: return WHITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Color>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Color>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Color>() {
            public Color findValueByNumber(int number) {
              return Color.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GameState.getDescriptor().getEnumTypes().get(0);
    }

    private static final Color[] VALUES = values();

    public static Color valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Color(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Color)
  }

  public interface IntersectionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 X = 1;
    /**
     * <code>required int32 X = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 X = 1;</code>
     */
    int getX();

    // required int32 Y = 2;
    /**
     * <code>required int32 Y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 Y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code Intersection}
   */
  public static final class Intersection extends
      com.google.protobuf.GeneratedMessage
      implements IntersectionOrBuilder {
    // Use Intersection.newBuilder() to construct.
    private Intersection(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Intersection(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Intersection defaultInstance;
    public static Intersection getDefaultInstance() {
      return defaultInstance;
    }

    public Intersection getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Intersection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameState.internal_static_Intersection_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameState.internal_static_Intersection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameState.Intersection.class, GameState.Intersection.Builder.class);
    }

    public static com.google.protobuf.Parser<Intersection> PARSER =
        new com.google.protobuf.AbstractParser<Intersection>() {
      public Intersection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Intersection(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Intersection> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 X = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>required int32 X = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 X = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // required int32 Y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>required int32 Y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GameState.Intersection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Intersection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Intersection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Intersection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Intersection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Intersection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GameState.Intersection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GameState.Intersection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GameState.Intersection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Intersection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GameState.Intersection prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Intersection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GameState.IntersectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameState.internal_static_Intersection_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameState.internal_static_Intersection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameState.Intersection.class, GameState.Intersection.Builder.class);
      }

      // Construct using GameState.Intersection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameState.internal_static_Intersection_descriptor;
      }

      public GameState.Intersection getDefaultInstanceForType() {
        return GameState.Intersection.getDefaultInstance();
      }

      public GameState.Intersection build() {
        GameState.Intersection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GameState.Intersection buildPartial() {
        GameState.Intersection result = new GameState.Intersection(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameState.Intersection) {
          return mergeFrom((GameState.Intersection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameState.Intersection other) {
        if (other == GameState.Intersection.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameState.Intersection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameState.Intersection) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 X = 1;
      private int x_ ;
      /**
       * <code>required int32 X = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 X = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 X = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 X = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // required int32 Y = 2;
      private int y_ ;
      /**
       * <code>required int32 Y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 Y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Intersection)
    }

    static {
      defaultInstance = new Intersection(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Intersection)
  }

  public interface PlacementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Intersection place = 1;
    /**
     * <code>required .Intersection place = 1;</code>
     */
    boolean hasPlace();
    /**
     * <code>required .Intersection place = 1;</code>
     */
    GameState.Intersection getPlace();
    /**
     * <code>required .Intersection place = 1;</code>
     */
    GameState.IntersectionOrBuilder getPlaceOrBuilder();

    // required .Color player = 2;
    /**
     * <code>required .Color player = 2;</code>
     */
    boolean hasPlayer();
    /**
     * <code>required .Color player = 2;</code>
     */
    GameState.Color getPlayer();
  }
  /**
   * Protobuf type {@code Placement}
   */
  public static final class Placement extends
      com.google.protobuf.GeneratedMessage
      implements PlacementOrBuilder {
    // Use Placement.newBuilder() to construct.
    private Placement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Placement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Placement defaultInstance;
    public static Placement getDefaultInstance() {
      return defaultInstance;
    }

    public Placement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Placement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              GameState.Intersection.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = place_.toBuilder();
              }
              place_ = input.readMessage(GameState.Intersection.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(place_);
                place_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              GameState.Color value = GameState.Color.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                player_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameState.internal_static_Placement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameState.internal_static_Placement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameState.Placement.class, GameState.Placement.Builder.class);
    }

    public static com.google.protobuf.Parser<Placement> PARSER =
        new com.google.protobuf.AbstractParser<Placement>() {
      public Placement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Placement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Placement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Intersection place = 1;
    public static final int PLACE_FIELD_NUMBER = 1;
    private GameState.Intersection place_;
    /**
     * <code>required .Intersection place = 1;</code>
     */
    public boolean hasPlace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Intersection place = 1;</code>
     */
    public GameState.Intersection getPlace() {
      return place_;
    }
    /**
     * <code>required .Intersection place = 1;</code>
     */
    public GameState.IntersectionOrBuilder getPlaceOrBuilder() {
      return place_;
    }

    // required .Color player = 2;
    public static final int PLAYER_FIELD_NUMBER = 2;
    private GameState.Color player_;
    /**
     * <code>required .Color player = 2;</code>
     */
    public boolean hasPlayer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Color player = 2;</code>
     */
    public GameState.Color getPlayer() {
      return player_;
    }

    private void initFields() {
      place_ = GameState.Intersection.getDefaultInstance();
      player_ = GameState.Color.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPlace()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPlace().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, place_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, player_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, place_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, player_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GameState.Placement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Placement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Placement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Placement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Placement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Placement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GameState.Placement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GameState.Placement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GameState.Placement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Placement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GameState.Placement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Placement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GameState.PlacementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameState.internal_static_Placement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameState.internal_static_Placement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameState.Placement.class, GameState.Placement.Builder.class);
      }

      // Construct using GameState.Placement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlaceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (placeBuilder_ == null) {
          place_ = GameState.Intersection.getDefaultInstance();
        } else {
          placeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        player_ = GameState.Color.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameState.internal_static_Placement_descriptor;
      }

      public GameState.Placement getDefaultInstanceForType() {
        return GameState.Placement.getDefaultInstance();
      }

      public GameState.Placement build() {
        GameState.Placement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GameState.Placement buildPartial() {
        GameState.Placement result = new GameState.Placement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (placeBuilder_ == null) {
          result.place_ = place_;
        } else {
          result.place_ = placeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.player_ = player_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameState.Placement) {
          return mergeFrom((GameState.Placement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameState.Placement other) {
        if (other == GameState.Placement.getDefaultInstance()) return this;
        if (other.hasPlace()) {
          mergePlace(other.getPlace());
        }
        if (other.hasPlayer()) {
          setPlayer(other.getPlayer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlace()) {
          
          return false;
        }
        if (!hasPlayer()) {
          
          return false;
        }
        if (!getPlace().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameState.Placement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameState.Placement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Intersection place = 1;
      private GameState.Intersection place_ = GameState.Intersection.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          GameState.Intersection, GameState.Intersection.Builder, GameState.IntersectionOrBuilder> placeBuilder_;
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public boolean hasPlace() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public GameState.Intersection getPlace() {
        if (placeBuilder_ == null) {
          return place_;
        } else {
          return placeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public Builder setPlace(GameState.Intersection value) {
        if (placeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          place_ = value;
          onChanged();
        } else {
          placeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public Builder setPlace(
          GameState.Intersection.Builder builderForValue) {
        if (placeBuilder_ == null) {
          place_ = builderForValue.build();
          onChanged();
        } else {
          placeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public Builder mergePlace(GameState.Intersection value) {
        if (placeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              place_ != GameState.Intersection.getDefaultInstance()) {
            place_ =
              GameState.Intersection.newBuilder(place_).mergeFrom(value).buildPartial();
          } else {
            place_ = value;
          }
          onChanged();
        } else {
          placeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public Builder clearPlace() {
        if (placeBuilder_ == null) {
          place_ = GameState.Intersection.getDefaultInstance();
          onChanged();
        } else {
          placeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public GameState.Intersection.Builder getPlaceBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPlaceFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      public GameState.IntersectionOrBuilder getPlaceOrBuilder() {
        if (placeBuilder_ != null) {
          return placeBuilder_.getMessageOrBuilder();
        } else {
          return place_;
        }
      }
      /**
       * <code>required .Intersection place = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          GameState.Intersection, GameState.Intersection.Builder, GameState.IntersectionOrBuilder> 
          getPlaceFieldBuilder() {
        if (placeBuilder_ == null) {
          placeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              GameState.Intersection, GameState.Intersection.Builder, GameState.IntersectionOrBuilder>(
                  place_,
                  getParentForChildren(),
                  isClean());
          place_ = null;
        }
        return placeBuilder_;
      }

      // required .Color player = 2;
      private GameState.Color player_ = GameState.Color.EMPTY;
      /**
       * <code>required .Color player = 2;</code>
       */
      public boolean hasPlayer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Color player = 2;</code>
       */
      public GameState.Color getPlayer() {
        return player_;
      }
      /**
       * <code>required .Color player = 2;</code>
       */
      public Builder setPlayer(GameState.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        player_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Color player = 2;</code>
       */
      public Builder clearPlayer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        player_ = GameState.Color.EMPTY;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Placement)
    }

    static {
      defaultInstance = new Placement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Placement)
  }

  public interface MomentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Color toMove = 1;
    /**
     * <code>required .Color toMove = 1;</code>
     */
    boolean hasToMove();
    /**
     * <code>required .Color toMove = 1;</code>
     */
    GameState.Color getToMove();

    // repeated .Placement boardState = 2;
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    java.util.List<GameState.Placement> 
        getBoardStateList();
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    GameState.Placement getBoardState(int index);
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    int getBoardStateCount();
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    java.util.List<? extends GameState.PlacementOrBuilder> 
        getBoardStateOrBuilderList();
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    GameState.PlacementOrBuilder getBoardStateOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Moment}
   */
  public static final class Moment extends
      com.google.protobuf.GeneratedMessage
      implements MomentOrBuilder {
    // Use Moment.newBuilder() to construct.
    private Moment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Moment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Moment defaultInstance;
    public static Moment getDefaultInstance() {
      return defaultInstance;
    }

    public Moment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Moment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              GameState.Color value = GameState.Color.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                toMove_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                boardState_ = new java.util.ArrayList<GameState.Placement>();
                mutable_bitField0_ |= 0x00000002;
              }
              boardState_.add(input.readMessage(GameState.Placement.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          boardState_ = java.util.Collections.unmodifiableList(boardState_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameState.internal_static_Moment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameState.internal_static_Moment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameState.Moment.class, GameState.Moment.Builder.class);
    }

    public static com.google.protobuf.Parser<Moment> PARSER =
        new com.google.protobuf.AbstractParser<Moment>() {
      public Moment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Moment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Moment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Color toMove = 1;
    public static final int TOMOVE_FIELD_NUMBER = 1;
    private GameState.Color toMove_;
    /**
     * <code>required .Color toMove = 1;</code>
     */
    public boolean hasToMove() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Color toMove = 1;</code>
     */
    public GameState.Color getToMove() {
      return toMove_;
    }

    // repeated .Placement boardState = 2;
    public static final int BOARDSTATE_FIELD_NUMBER = 2;
    private java.util.List<GameState.Placement> boardState_;
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    public java.util.List<GameState.Placement> getBoardStateList() {
      return boardState_;
    }
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    public java.util.List<? extends GameState.PlacementOrBuilder> 
        getBoardStateOrBuilderList() {
      return boardState_;
    }
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    public int getBoardStateCount() {
      return boardState_.size();
    }
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    public GameState.Placement getBoardState(int index) {
      return boardState_.get(index);
    }
    /**
     * <code>repeated .Placement boardState = 2;</code>
     */
    public GameState.PlacementOrBuilder getBoardStateOrBuilder(
        int index) {
      return boardState_.get(index);
    }

    private void initFields() {
      toMove_ = GameState.Color.EMPTY;
      boardState_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasToMove()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBoardStateCount(); i++) {
        if (!getBoardState(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, toMove_.getNumber());
      }
      for (int i = 0; i < boardState_.size(); i++) {
        output.writeMessage(2, boardState_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, toMove_.getNumber());
      }
      for (int i = 0; i < boardState_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, boardState_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GameState.Moment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Moment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Moment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameState.Moment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameState.Moment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Moment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GameState.Moment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GameState.Moment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GameState.Moment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GameState.Moment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GameState.Moment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Moment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements GameState.MomentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameState.internal_static_Moment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameState.internal_static_Moment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameState.Moment.class, GameState.Moment.Builder.class);
      }

      // Construct using GameState.Moment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBoardStateFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toMove_ = GameState.Color.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (boardStateBuilder_ == null) {
          boardState_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          boardStateBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameState.internal_static_Moment_descriptor;
      }

      public GameState.Moment getDefaultInstanceForType() {
        return GameState.Moment.getDefaultInstance();
      }

      public GameState.Moment build() {
        GameState.Moment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GameState.Moment buildPartial() {
        GameState.Moment result = new GameState.Moment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.toMove_ = toMove_;
        if (boardStateBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            boardState_ = java.util.Collections.unmodifiableList(boardState_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.boardState_ = boardState_;
        } else {
          result.boardState_ = boardStateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameState.Moment) {
          return mergeFrom((GameState.Moment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameState.Moment other) {
        if (other == GameState.Moment.getDefaultInstance()) return this;
        if (other.hasToMove()) {
          setToMove(other.getToMove());
        }
        if (boardStateBuilder_ == null) {
          if (!other.boardState_.isEmpty()) {
            if (boardState_.isEmpty()) {
              boardState_ = other.boardState_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBoardStateIsMutable();
              boardState_.addAll(other.boardState_);
            }
            onChanged();
          }
        } else {
          if (!other.boardState_.isEmpty()) {
            if (boardStateBuilder_.isEmpty()) {
              boardStateBuilder_.dispose();
              boardStateBuilder_ = null;
              boardState_ = other.boardState_;
              bitField0_ = (bitField0_ & ~0x00000002);
              boardStateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBoardStateFieldBuilder() : null;
            } else {
              boardStateBuilder_.addAllMessages(other.boardState_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToMove()) {
          
          return false;
        }
        for (int i = 0; i < getBoardStateCount(); i++) {
          if (!getBoardState(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameState.Moment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameState.Moment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Color toMove = 1;
      private GameState.Color toMove_ = GameState.Color.EMPTY;
      /**
       * <code>required .Color toMove = 1;</code>
       */
      public boolean hasToMove() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Color toMove = 1;</code>
       */
      public GameState.Color getToMove() {
        return toMove_;
      }
      /**
       * <code>required .Color toMove = 1;</code>
       */
      public Builder setToMove(GameState.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        toMove_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Color toMove = 1;</code>
       */
      public Builder clearToMove() {
        bitField0_ = (bitField0_ & ~0x00000001);
        toMove_ = GameState.Color.EMPTY;
        onChanged();
        return this;
      }

      // repeated .Placement boardState = 2;
      private java.util.List<GameState.Placement> boardState_ =
        java.util.Collections.emptyList();
      private void ensureBoardStateIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          boardState_ = new java.util.ArrayList<GameState.Placement>(boardState_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          GameState.Placement, GameState.Placement.Builder, GameState.PlacementOrBuilder> boardStateBuilder_;

      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public java.util.List<GameState.Placement> getBoardStateList() {
        if (boardStateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(boardState_);
        } else {
          return boardStateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public int getBoardStateCount() {
        if (boardStateBuilder_ == null) {
          return boardState_.size();
        } else {
          return boardStateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public GameState.Placement getBoardState(int index) {
        if (boardStateBuilder_ == null) {
          return boardState_.get(index);
        } else {
          return boardStateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder setBoardState(
          int index, GameState.Placement value) {
        if (boardStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardStateIsMutable();
          boardState_.set(index, value);
          onChanged();
        } else {
          boardStateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder setBoardState(
          int index, GameState.Placement.Builder builderForValue) {
        if (boardStateBuilder_ == null) {
          ensureBoardStateIsMutable();
          boardState_.set(index, builderForValue.build());
          onChanged();
        } else {
          boardStateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder addBoardState(GameState.Placement value) {
        if (boardStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardStateIsMutable();
          boardState_.add(value);
          onChanged();
        } else {
          boardStateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder addBoardState(
          int index, GameState.Placement value) {
        if (boardStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBoardStateIsMutable();
          boardState_.add(index, value);
          onChanged();
        } else {
          boardStateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder addBoardState(
          GameState.Placement.Builder builderForValue) {
        if (boardStateBuilder_ == null) {
          ensureBoardStateIsMutable();
          boardState_.add(builderForValue.build());
          onChanged();
        } else {
          boardStateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder addBoardState(
          int index, GameState.Placement.Builder builderForValue) {
        if (boardStateBuilder_ == null) {
          ensureBoardStateIsMutable();
          boardState_.add(index, builderForValue.build());
          onChanged();
        } else {
          boardStateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder addAllBoardState(
          java.lang.Iterable<? extends GameState.Placement> values) {
        if (boardStateBuilder_ == null) {
          ensureBoardStateIsMutable();
          super.addAll(values, boardState_);
          onChanged();
        } else {
          boardStateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder clearBoardState() {
        if (boardStateBuilder_ == null) {
          boardState_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          boardStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public Builder removeBoardState(int index) {
        if (boardStateBuilder_ == null) {
          ensureBoardStateIsMutable();
          boardState_.remove(index);
          onChanged();
        } else {
          boardStateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public GameState.Placement.Builder getBoardStateBuilder(
          int index) {
        return getBoardStateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public GameState.PlacementOrBuilder getBoardStateOrBuilder(
          int index) {
        if (boardStateBuilder_ == null) {
          return boardState_.get(index);  } else {
          return boardStateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public java.util.List<? extends GameState.PlacementOrBuilder> 
           getBoardStateOrBuilderList() {
        if (boardStateBuilder_ != null) {
          return boardStateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(boardState_);
        }
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public GameState.Placement.Builder addBoardStateBuilder() {
        return getBoardStateFieldBuilder().addBuilder(
            GameState.Placement.getDefaultInstance());
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public GameState.Placement.Builder addBoardStateBuilder(
          int index) {
        return getBoardStateFieldBuilder().addBuilder(
            index, GameState.Placement.getDefaultInstance());
      }
      /**
       * <code>repeated .Placement boardState = 2;</code>
       */
      public java.util.List<GameState.Placement.Builder> 
           getBoardStateBuilderList() {
        return getBoardStateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          GameState.Placement, GameState.Placement.Builder, GameState.PlacementOrBuilder> 
          getBoardStateFieldBuilder() {
        if (boardStateBuilder_ == null) {
          boardStateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              GameState.Placement, GameState.Placement.Builder, GameState.PlacementOrBuilder>(
                  boardState_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          boardState_ = null;
        }
        return boardStateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Moment)
    }

    static {
      defaultInstance = new Moment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Moment)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Intersection_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Intersection_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Placement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Placement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Moment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Moment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017GameState.proto\"$\n\014Intersection\022\t\n\001X\030\001" +
      " \002(\005\022\t\n\001Y\030\002 \002(\005\"A\n\tPlacement\022\034\n\005place\030\001 " +
      "\002(\0132\r.Intersection\022\026\n\006player\030\002 \002(\0162\006.Col" +
      "or\"@\n\006Moment\022\026\n\006toMove\030\001 \002(\0162\006.Color\022\036\n\n" +
      "boardState\030\002 \003(\0132\n.Placement*(\n\005Color\022\t\n" +
      "\005EMPTY\020\000\022\t\n\005BLACK\020\001\022\t\n\005WHITE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Intersection_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Intersection_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Intersection_descriptor,
              new java.lang.String[] { "X", "Y", });
          internal_static_Placement_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Placement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Placement_descriptor,
              new java.lang.String[] { "Place", "Player", });
          internal_static_Moment_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Moment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Moment_descriptor,
              new java.lang.String[] { "ToMove", "BoardState", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
